/*
##########################################################################
DO NOT EDIT THIS FILE DIRECTLY! IT IS GENERATED FROM DATABASE INFORMATION.
##########################################################################
 */



#ifndef MUSYS_DYNAMIC_HPP
#define MUSYS_DYNAMIC_HPP

#include <vector>
#include <memory>
#include "metric.hpp"


namespace munits {

    enum metrics {
        Length = 0,
        Mass = 1,
        Time = 2,
        ElectricCurrency = 3,
        Temperature = 4,
        AmountOfSubstance = 5,
        LuminousIntensity = 6,
        Area = 7,
        Volume = 8,
        VolumetricFlow = 9,
        MolarConcentration = 10,
        Acceleration = 11,
        Force = 12,
        Velocity = 13,
        Concentration = 14,
        _Last

    };


    const std::vector<munits::Metric> & GetMatrix();


}
#endif //MUSYS_DYNAMIC_HPP
